import type { Contact, Conversation } from "./types";

export const SEED_CONTACTS: Contact[] = [
  {
    id: "c1",
    name: "Sarah Chen",
    company: "Vertex AI",
    role: "VP Product",
    location: "San Francisco, CA",
    phone: "+1 415-555-0142",
    email: "sarah.chen@vertexai.com",
    linkedin: "linkedin.com/in/sarahchen",
    category: "Investor",
    status: "Active",
    whereMet: "TechCrunch Disrupt",
    dateMet: "2025-11-15",
    notes: "Interested in B2B SaaS. Has a strong network in enterprise.",
    createdAt: "2025-11-15T10:00:00.000Z",
    updatedAt: "2025-11-15T10:00:00.000Z",
  },
  {
    id: "c2",
    name: "Marcus Rivera",
    company: "Rivera Capital",
    role: "Managing Partner",
    location: "Austin, TX",
    phone: "+1 512-555-0198",
    email: "marcus@riveracapital.com",
    linkedin: "linkedin.com/in/marcusrivera",
    category: "Investor",
    status: "Warm",
    whereMet: "SXSW Panel",
    dateMet: "2025-10-20",
    notes: "Focuses on fintech and climate tech. Prefers warm intros.",
    createdAt: "2025-10-20T14:30:00.000Z",
    updatedAt: "2025-10-20T14:30:00.000Z",
  },
  {
    id: "c3",
    name: "Elena Vasquez",
    company: "GrowthLoop",
    role: "Head of Partnerships",
    location: "Miami, FL",
    phone: "+1 305-555-0167",
    email: "elena@growthloop.io",
    linkedin: "linkedin.com/in/elenavasquez",
    category: "Partner",
    status: "Active",
    whereMet: "Mutual friend intro",
    dateMet: "2025-12-01",
    notes: "Looking for integration partners. Very responsive on LinkedIn.",
    createdAt: "2025-12-01T09:00:00.000Z",
    updatedAt: "2025-12-01T09:00:00.000Z",
  },
];

export const SEED_CONVERSATIONS: Conversation[] = [
  {
    id: "v1",
    contactId: "c1",
    date: "2025-12-10",
    context: "Coffee at Sightglass, SF",
    notes: "Deep dive on our product roadmap. She asked smart questions about unit economics.",
    interests: "AI tooling for enterprise, team productivity",
    problems: "Hard to evaluate early-stage AI startups",
    opportunities: "Potential intro to her portfolio companies",
    promises: "Send deck and 1-pager by Friday",
    nextStep: "Follow up after she reviews materials",
    followUpDate: "2025-12-20",
    createdAt: "2025-12-10T16:00:00.000Z",
  },
  {
    id: "v2",
    contactId: "c2",
    date: "2025-11-05",
    context: "Zoom call",
    notes: "Discussed market timing and competitive landscape in fintech.",
    interests: "Embedded finance, B2B payments",
    problems: "Regulatory complexity in cross-border payments",
    opportunities: "Could co-invest if we raise a seed round",
    promises: "Intro to their legal advisor",
    nextStep: "Send monthly update email",
    followUpDate: "2026-01-15",
    createdAt: "2025-11-05T11:00:00.000Z",
  },
  {
    id: "v3",
    contactId: "c3",
    date: "2025-12-15",
    context: "LinkedIn video call",
    notes: "Explored partnership structure. Both sides see synergy in CRM integrations.",
    interests: "API partnerships, co-marketing",
    problems: "Their team is stretched thin on integrations",
    opportunities: "Pilot integration in Q1",
    promises: "Share technical docs and sandbox access",
    nextStep: "Schedule technical call with her eng lead",
    followUpDate: "2026-01-05",
    createdAt: "2025-12-15T13:30:00.000Z",
  },
];
