/** Lightweight Control Library Index — labels only; AI requests one copy row next. */

export function buildLibraryIndexBrief(): string {
  return [
    "=== LIBRARY INDEX ===",
    "Copy from Control → Library. Nav rows open drawers — they are NOT copy buttons.",
    "After this index, request ONE exact visible copy-row label — not a nav name.",
    "",
    "RULES vs DATA",
    "- Operating rules (MAF, Entry Solver, R$, TF governance) → Control → MTA Mechanics only.",
    "- Do NOT ask for separate MAF protocol or Entry Solver copies.",
    "- Library rows below are DATA / technical procedure — not a second constitution.",
    "",
    "Technical Analysis (Library nav)",
    "- Copy row: MTAE protocol",
    "- MTAE: structure, zones, targets, invalidation, participation",
    "- No capital decision, no Entry Solver, no Scout verdict",
    "",
    "Playbook (Library nav)",
    "- Copy row: Playbook snapshot",
    "- Reusable methods, entry families (A rebound vs B trend continuation), checklists, experiments",
    "",
    "Scout Desk (Library nav)",
    "- Copy row: Scout desk overview",
    "- Decision, entry, stop, target, R, opportunity quality, capital gate",
    "",
    "MAF (Library nav)",
    "- No separate protocol copy row — MAF rules are inside MTA Mechanics",
    "- Drawer reserved for future MAF experiment/data snapshots only",
    "- FORBIDDEN: do not ask the human to copy Learning — that nav label is retired",
    "",
    "Also available (primary / windows — not Library):",
    "- MTA Mechanics — canonical constitution (Control → MTA Mechanics)",
    "- Apply schema contract — second copy row under MTA Mechanics (Apply Mode only)",
    "- Analyze with AI — Stock File window CTA (preferred ticker loop; includes full Mechanics)",
    "- Apply — paste Validate Accept (write path)",
    "- Dashboard snapshot — Dashboard window menu",
    "- {TICKER} · {ID} historical attribution evidence — historical/planless closed trade detail (not accepted MAF)",
    "",
    "=== REQUEST ===",
    "Ask the human to copy the exact visible copy-row label you need next.",
  ].join("\n");
}
