/** Lightweight Control Library Index — labels only; AI requests one copy row next. */

export function buildLibraryIndexBrief(): string {
  return [
    "=== LIBRARY INDEX ===",
    "Copy from Control → Library. Nav rows open drawers — they are NOT copy buttons.",
    "After this index, request ONE exact visible copy-row label — not a nav name.",
    "",
    "Technical Analysis (Library nav)",
    "- Copy row: MTAE protocol",
    "- MTAE: structure, zones, targets, invalidation, participation",
    "- No capital decision, no Entry Solver, no Scout verdict",
    "",
    "Playbook (Library nav)",
    "- Copy row: Playbook snapshot",
    "- Reusable methods, entry families (A rebound vs B trend continuation), checklists, experiments",
    "",
    "Scout Desk (Library nav)",
    "- Copy row: Scout desk overview",
    "- Decision, entry, stop, target, R, opportunity quality, capital gate",
    "",
    "MAF (Library nav)",
    "- Copy row: MAF attribution protocol",
    "- Observation / Learning Outcome domain lives elsewhere; Control exposes MAF protocol only",
    "- FORBIDDEN: do not ask the human to copy Learning — that nav label is retired; use MAF → MAF attribution protocol",
    "",
    "Also available (primary / windows — not Library):",
    "- MTA Mechanics — constitution copy row (Control → MTA Mechanics)",
    "- Apply schema contract — second copy row under MTA Mechanics (not primary nav)",
    "- Analyze with AI — Stock File window CTA (preferred ticker loop)",
    "- Apply — paste Validate Accept (write path)",
    "- Dashboard snapshot — Control home (first copy row) or Dashboard window menu",
    "",
    "=== REQUEST ===",
    "Ask the human to copy the exact visible copy-row label you need next.",
  ].join("\n");
}
