import { DEFAULT_AI_BLOCK_REQUEST } from "./ai-block";
import { buildMatrixMechanicsBrief } from "./matrix-mechanics-brief";

/** Bump when mechanics snapshot content changes materially. */
export const MATRIX_MECHANICS_REVISION = 7;

/**
 * Full Matrix Mechanics export — paste once per external AI session to train rules.
 * Window snapshots use the brief prefix automatically; this is the expanded constitution.
 */
export function buildMatrixMechanicsSnapshot(): string {
  return [
    "=== MATRIX MECHANICS SNAPSHOT ===",
    `mechanics_revision:${MATRIX_MECHANICS_REVISION}`,
    "",
    buildMatrixMechanicsBrief(),
    "",
    "=== APPLY GATE (non-negotiable) ===",
    "Default: Analysis Mode — natural discussion, no JSON, no persistence.",
    "Apply Mode: only after explicit intent (Save, Create, Update, Record, Apply, Import, Propose JSON, Persist to Matrix).",
    "External AI proposes. Matrix never auto-writes.",
    "Flow: Copy snapshot → discuss in Analysis Mode → user requests Apply → ONE JSON block → Import in Inbox → human Apply.",
    "",
    "=== AI BLOCK TYPES ===",
    "Scouting layer:",
    "- stock-case-create — new Stock Profile (+ optional initialScout)",
    "- evidence-add — append market evidence row",
    "- file-update — update an existing Stock File; may include initialScout to backfill a missing Scout Plan when no linked active plan exists",
    "- scout-assessment — validate dossier (reasons + challenges required)",
    "- decision-update — update verdict and/or tactical parameters (entry, stop, target) on an existing Scout Plan",
    "",
    "Execution layer:",
    "- trade-proposal — new trade",
    "- trade-update — change stop, target, shares, status, notes, etc. (primary mutation)",
    "- trade-close — close at exit price",
    "- trade-review — post-close quality + mistakes + lesson",
    "- analysis — qualitative notes on a trade",
    "",
    "Method layer:",
    "- playbook-create / playbook-update",
    "",
    "=== COMMON AI ERRORS TO AVOID ===",
    "- Generating JSON during Analysis Mode or before explicit Apply intent",
    "- Inventing trades, prices, or P/L not in the snapshot",
    "- Using structural invalidation or zone lows as stop for R:R when plan.strategy_stop differs",
    "- Skipping Stock Profile before proposing entry",
    "- Overriding invalidation or minimum R:R without explicit user approval",
    "- Returning multiple blocks or markdown without a single JSON block",
    "- Using curly/smart quotes in JSON (use ASCII double quotes only)",
    "- Applying changes silently — always return a block for Inbox Apply",
    "- Encouraging entry merely because the thesis is bullish",
    "- Treating minimum 3R as automatic approval",
    "- Evaluating trades independently without considering scarce monthly risk capacity",
    "- Using extended targets to make a mediocre opportunity appear attractive",
    "- Treating a missed trade as a negative outcome",
    "- Recreating a Stock File merely because initialScout was omitted",
    "- Using trade-update before a Scout Plan and Trade exist",
    "- Creating duplicate Scout Plans during a repair",
    "- Rejecting a valid repair when the Stock File exists but the linked Scout Plan is missing",
    "",
    "=== LAYER OWNERSHIP ===",
    "- Playbook (HOW): reusable method, checklist, horizons",
    "- Stock Profile (WHO): ticker thesis, levels, invalidation, evidence",
    "- Scout PLAN: tactical window linked to profile + playbook",
    "- Trade: execution record — mutate via trade-update / trade-close only",
    "",
    "=== SNAPSHOT MENU ===",
    "Ask the human to copy a named snapshot from Control panel when you need depth.",
    "Scout PLAN snapshot includes strategy_stop + planned_rr (never structural stop for R).",
    "Stock profile snapshot includes thesis_invalidation (structural) — do not substitute for strategy stop.",
    "",
    "=== REQUEST ===",
    DEFAULT_AI_BLOCK_REQUEST.trim(),
  ].join("\n");
}
