import { DEFAULT_AI_BLOCK_REQUEST } from "./ai-block";
import { buildMatrixMechanicsBrief } from "./matrix-mechanics-brief";

/** Bump when mechanics snapshot content changes materially. */
export const MATRIX_MECHANICS_REVISION = 27;

/**
 * Full Matrix Mechanics export — paste once per external AI session to train rules.
 * Window snapshots use the brief prefix automatically; this is the expanded constitution.
 */
export function buildMatrixMechanicsSnapshot(): string {
  return [
    "=== MATRIX MECHANICS SNAPSHOT ===",
    `mechanics_revision:${MATRIX_MECHANICS_REVISION}`,
    "",
    buildMatrixMechanicsBrief(),
    "",
    "=== APPLY GATE (non-negotiable) ===",
    "Default: Analysis Mode — natural discussion, no JSON, no persistence.",
    "Apply Mode: only after explicit intent (Save, Create, Update, Record, Apply, Import, Propose JSON, Persist to MTA).",
    "External AI proposes. MTA never auto-writes.",
    "Flow: Copy snapshot → discuss in Analysis Mode → user requests Apply → ONE JSON block → Import in Inbox → human Apply.",
    "SCHEMA-FIRST: before Apply JSON, read Apply Schema Contract. Never invent keys. stock-case-create requires entry+stop+target.",
    "",
    "=== AI BLOCK TYPES ===",
    "Scouting layer:",
    "- stock-case-create — new Stock Profile (+ REQUIRED initialScout plannedEntry/stopPrice/targetPrice)",
    "- stock-case-delete — remove Stock Profile (confirmDelete: true required)",
    "- evidence-add — append market evidence row",
    "- file-update — update an existing Stock File; may include initialScout to backfill a missing Scout Plan when no linked active plan exists",
    "- scout-plan-create — NEW Scout Plan window on an existing Stock File (same ticker; allocates NEW PLAN-xxx; optional initial verdict)",
    "- technical-assessment — MTAE Evidence First multi-TF JSON (Supports/Targets/Bias/Conf per TF → Integrated → Profile Notes) — NEVER Entry Solver / Scout verdicts / capital",
    "- technical-calibration — human correction to MTAE procedure (support rank, targets, volume/movement overclaims, etc.)",
    "- scout-assessment — validate dossier (reasons + challenges required)",
    "- decision-update — update verdict and/or tactical parameters (entry, stop, target) on an EXISTING Scout Plan",
    "",
    "Execution layer:",
    "- trade-proposal — new trade",
    "- trade-update — change stop, target, shares, status, notes, etc. (primary mutation)",
    "- trade-close — close at exit price",
    "- trade-review — post-close quality + mistakes + lesson",
    "- analysis — qualitative notes on a trade",
    "- attribution — MAF component attribution (process quality ≠ P/L; never invent prices)",
    "- observation-update — Observation Engine (target/invalidation timestamps, MFE/MAE)",
    "",
    "Method layer:",
    "- playbook-create / playbook-update",
    "",
    "=== COMMON AI ERRORS TO AVOID ===",
    "- Generating JSON during Analysis Mode or before explicit Apply intent",
    "- Inventing trades, prices, or P/L not in the snapshot",
    "- Using structural invalidation or zone lows as stop for R:R when plan.strategy_stop differs",
    "- Skipping Stock Profile before proposing entry",
    "- Overriding invalidation or minimum R:R without explicit user approval",
    "- Returning multiple blocks or markdown without a single JSON block",
    "- Using curly/smart quotes in JSON (use ASCII double quotes only)",
    "- Applying changes silently — always return a block for Inbox Apply",
    "- Encouraging entry merely because the thesis is bullish",
    "- Treating minimum 3R / maximumEntry as the recommended entry",
    "- Stopping the Entry Solver at feasibility without Entry Optimization",
    "- Evaluating trades independently without considering scarce monthly risk capacity",
    "- Using extended targets to make a mediocre opportunity appear attractive",
    "- Treating a missed trade as a negative outcome",
    "- Recreate a Stock File because initialScout was omitted — use file-update.initialScout backfill instead.",
    "- Use decision-update or file-update.initialScout when the human asked for a NEW plan window — use scout-plan-create instead",
    "- stock-case-create for a ticker that already has a Stock File just to open a new trade or plan",
    "- Reuse a closed trade id (H00x) or pretend a finished PLAN is a blank new window",
    "- Tell the human to delete prior trades/plans/Stock File so a new same-ticker idea can be saved",
    "- Using trade-update before a Scout Plan and Trade exist",
    "- Creating duplicate Scout Plans during a repair",
    "- Rejecting a valid repair when the Stock File exists but the linked Scout Plan is missing",
    "",
    "=== LAYER OWNERSHIP ===",
    "- Playbook (HOW): reusable method, checklist, horizons",
    "- Stock Profile (WHO): ONE dossier per ticker — update, do not recreate for each trade",
    "- Scout PLAN: ONE tactical window — new opportunity → scout-plan-create → NEW PLAN id",
    "- Trade (H00x): ONE fill — new execution → new trade id; closed trades stay in history",
    "- MAF experiment: ONE learning record after close/observation — component attribution, not a journal",
    "",
    "=== SNAPSHOT MENU ===",
    "Preferred Stock File loop (MTA-002A): Analyze with AI → chat → Apply AI Result → Open Scout.",
    "Analyze with AI copies one package: operative prompt + Mechanics + MTAE + dossier + active Scout.",
    "Ask the human to copy named snapshots from Control when they need a slice only",
    "(Mechanics brief, Technical analysis / MTAE, Playbook, Stock file, Scout desk) or Trade window.",
    "Closed-trade forensic export lives ONLY on /trades/{ID} — never as a Control home section.",
    "MTAE is Control → Technical analysis — not Playbook, not Mechanics.",
    "Scout PLAN snapshot includes strategy_stop + planned_rr (never structural stop for R).",
    "Stock profile snapshot includes thesis_invalidation (structural) — do not substitute for strategy stop.",
    "",
    "=== REQUEST ===",
    DEFAULT_AI_BLOCK_REQUEST.trim(),
  ].join("\n");
}
